name: Mac Builds

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_NO_TESTS_ACTION: error

jobs:
  build:
    runs-on: ${{matrix.image}}
    strategy:
      fail-fast: false
      matrix:
        image: [macos-14, macos-15, macos-15-intel]
        build_type: [Debug, Release]
        std: [14, 17]

    steps:
    - uses: actions/checkout@v6

    - name: Configure
      run: |
        cmake --preset basic-tests -GNinja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCATCH_BUILD_EXAMPLES=ON \
              -DCATCH_BUILD_EXTRA_TESTS=ON

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build -j
